### PR TITLE
CommunicationController: allow specific services to be selected by name

### PR DESCRIPTION
**Pull request by brmeyer**

### CODE REVIEW

**Comment by sirken** [comment]
@brmeyer So now the `service` QueryParam is being looked for, and if it exists then only those services are synced. If it doesn't exist, then all communication services are synced

**Comment by sirken** [comment]
@brmeyer Does `EmailConroller` also need updates? The IDE is complaining about number of parameters

image

Something like:
image

**Comment by brmeyer** [comment]
WHOOPS! Good catch! And correct about the param being optional.

**Review by sirken — COMMENTED** [review]
Overall makes sense. I also added matching changes to `EmailController` but not sure if they're needed?

**Pull request merged**
